import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'vitest/config';
import { playwright } from '@vitest/browser-playwright';
import adapter from '@sveltejs/adapter-auto';
import { sveltekit } from '@sveltejs/kit/vite';
import path from 'path';
import fs from 'node:fs';

function generateImageList() {
	return {
		name: 'generate-image-list',

		buildStart() {
			const dir = path.resolve('static/icons');
			const dir2 = path.resolve('static/koroks');

			const files = fs
				.readdirSync(dir)
				.filter((file) => /\.(png|jpe?g|webp|gif)$/i.test(file))
				.sort();

			let output = `
/** Generated by vite.config.ts if icons or koroks are not updating restart server */
export const iconImages = ${JSON.stringify(files.map((file) => `icons/${file}`))};
`;

			const files2 = fs
				.readdirSync(dir2)
				.filter((file) => {
					if (/k_(0|[1-9][0-9]*)\.(png|jpe?g|webp|gif)$/i.test(file)) {
						return true;
					}
					console.error(`Skipping ${file}`);
					return false;
				})
				.sort(
					(a, b) =>
						Number(a.match(/(?<=k_)(0|[1-9][0-9]*)(?=\.png|\.jpe?g|\.webp|\.gif)/)?.[0] ?? 0) -
						Number(b.match(/(?<=k_)(0|[1-9][0-9]*)(?=\.png|\.jpe?g|\.webp|\.gif)/)?.[0] ?? 0)
				);

			output += `
/** Generated by vite.config.ts if icons or koroks are not updating restart server
  Images must follow this regex /k_(0|[1-9][0-9]*)\\.(png|jpe?g|webp|gif)$/
*/
export const korokImages = ${JSON.stringify(files2)};
`;

			fs.writeFileSync(path.resolve('src/lib/generated/images.ts'), output);
		}
	};
}
export default defineConfig({
	plugins: [
		tailwindcss(),
		generateImageList(),
		sveltekit({
			compilerOptions: {
				// Force runes mode for the project, except for libraries. Can be removed in svelte 6.
				runes: ({ filename }) =>
					filename.split(/[/\\]/).includes('node_modules') ? undefined : true,
				experimental: { async: true }
			},

			// adapter-auto only supports some environments, see https://svelte.dev/docs/kit/adapter-auto for a list.
			// If your environment is not supported, or you settled on a specific environment, switch out the adapter.
			// See https://svelte.dev/docs/kit/adapters for more information about adapters.
			adapter: adapter(),
			experimental: { remoteFunctions: true }
		})
	],
	resolve: {
		alias: {
			$lib: path.resolve('./src/lib')
		}
	},
	optimizeDeps: {
		exclude: ['maplibre-gl']
	},
	test: {
		expect: { requireAssertions: true },
		projects: [
			{
				extends: './vite.config.ts',
				test: {
					name: 'client',
					browser: {
						enabled: true,
						provider: playwright(),
						instances: [{ browser: 'chromium', headless: true }]
					},
					include: ['src/**/*.svelte.{test,spec}.{js,ts}'],
					exclude: ['src/lib/server/**']
				}
			},

			{
				extends: './vite.config.ts',
				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}']
				}
			}
		]
	}
});
